version: '3.6'
services:
  backend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/go/src/projectcorp
    links:
      - postgresprojectcorp
    depends_on:
      - postgresprojectcorp
    networks:
      - projectcorp

  postgresprojectcorp:
    restart: always
    build: ./databaseMigration
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=projectcorpdb
      - POSTGRES_USER=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./databaseMigration:/go/src/projectcorp/databaseMigration
    networks:
      - projectcorp

networks:
  projectcorp:
    name: projectcorp