version: '3.6'
services:
  corp_go:
    restart: always
    build:
      dockerfile: deploy/golang.Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/go/src/projectcorp
    links:
      - corp_postgres
    depends_on:
      - corp_postgres
    networks:
      - projectcorp

  corp_postgres:
    restart: always
    build:
      dockerfile: deploy/postgres.Dockerfile
      context: .
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=corp_db
      - POSTGRES_USER=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./migration:/go/src/projectcorp/migration
    networks:
      - projectcorp

networks:
  projectcorp:
    name: projectcorp